### ISSUE TITLE
Input notes to the front end

### ISSUE THREAD

**Issue by MarcusElgKTH** [INDAPlus21/danteac-eliased-faysalbm-melg-project#6]
AIn kommer behöva några toner att utgå ifrån. Vi kanske även kan ha instälnningar för bpm osv?

**Comment by MarcusElgKTH** [comment]
Maybe we have to have some option to control how many notes it should generate. Like a dropdown of 5/10/25/50?

**Comment by MazeofIth** [comment]
I think we can decide after we've seen how long it takes to generate a couple notes. As for now we start with 10
